### ISSUE TITLE
Proper Encryption of passwords(part of project 1 prep, day 10 assignment)

### ISSUE THREAD

**Issue by zachrickert** [bitedgeco/survivor-pool#10]
The site will ensure that user passwords and and keys are properly encrypted to minimize possible threats.

This relates to the user story:
As a site user I want to be able to sign up/log in/log out from any page so that I can participate in the pool.

**Comment by derekmhewitt** [comment]
Related to issue #10.  Check credentials is comparing against encrypted pws and storing them only encrypted.  Last piece: when we accept pws from the user to sign up we also need to encrypt them before storing.
