### ISSUE TITLE
Persist participants selections (part of project 1 prep, day 10 assignment) 

### ISSUE THREAD

**Issue by bitedgeco** [bitedgeco/survivor-pool#5]
We will need a participants table with 1 row per participant. The tables columns will be

id (int auto incrementing)
user_name (TEXT)
password (hashed)
alive (bolian, initialized to TRUE)
week1_selection (TEXT)
week2_selection (TEXT)
...
week17_selection (TEXT)

When a participant makes a selection it should be recorded on their roe.

When a user's selection loses their alive bolian switches to FALSE.

The user story this relates to is
_As a pool participant I want to see a schedule of games divided by week so that I can select a team for future weeks._

**Comment by derekmhewitt** [comment]
We refactored this task a bit - 
Participant selections will be persisted in a table join between users and events called "Picks".  We coded this yesterday.  The games are now displaying on the page, the last thing to do is get the participants selections to call the _add_pick method on the User object via an ajax post request.

**Comment by bitedgeco** [comment]
To do Make week 0 and 18 not a things
