### ISSUE TITLE
Authentication of username and password (part of project 1 prep, day 10 assignment)

### ISSUE THREAD

**Issue by zachrickert** [bitedgeco/survivor-pool#7]
Once a username and password is submitted, the app with have to authenticate the user.  Passing back any appropriate tokens to the user.

This relates to the user story:
As a site user I want to be able to sign up/log in/log out from any page so that I can participate in the pool.

**Comment by derekmhewitt** [comment]
branch 'auth'

**Comment by derekmhewitt** [comment]
Users model setup and they're populating in db, check_credentials function written.
